import type { Language } from "@/lib/i18n";

const copy = {
  vi: {
    nav: { explore: "Khám phá", categories: "Danh mục", trending: "Thịnh hành" },
    common: {
      viewAll: "Xem tất cả",
      loading: "Đang tải...",
      retry: "Thử lại",
      downloads: "lượt tải",
      keyboards: "giao diện",
      previous: "Trang trước",
      next: "Trang sau",
      page: "Trang",
      of: "trên",
    },
    home: {
      badge: "Thư viện theme bàn phím điện thoại cho iOS và Android",
      title: "Mỗi lần gõ, một chút dễ thương",
      description:
        "Xem trước nhiều hình ảnh thực tế và tải trọn bộ file theme pastel, anime, tối giản cho bàn phím điện thoại của bạn.",
      search: "Tìm Sakura, anime, pastel...",
      searchAction: "Tìm giao diện",
      featured: "Nổi bật hôm nay",
      featuredDesc: "Những theme bàn phím điện thoại được cộng đồng yêu thích và đội ngũ tuyển chọn.",
      trending: "Đang thịnh hành",
      trendingDesc: "Các giao diện có nhiều lượt tải nhất gần đây.",
      categories: "Khám phá theo phong cách",
      categoriesDesc: "Bắt đầu nhanh với một danh mục hợp gu của bạn.",
      discordTitle: "Cùng nhau làm bàn phím đẹp hơn",
      discordDesc: "Tham gia Discord để nhận theme cộng đồng, chia sẻ màn hình bàn phím và gặp các creator.",
      discordAction: "Tham gia Discord",
    },
    explore: {
      eyebrow: "Thư viện theme điện thoại",
      title: "Tìm theme bàn phím dành cho bạn",
      description: "Lọc theo phong cách và nền tảng. Mọi lựa chọn đều được lưu trên URL.",
      search: "Tìm theo tên giao diện...",
      category: "Danh mục",
      allCategories: "Tất cả danh mục",
      platform: "Nền tảng",
      allPlatforms: "Mọi nền tảng",
      sort: "Sắp xếp",
      latest: "Mới nhất",
      popular: "Phổ biến nhất",
      liked: "Được yêu thích",
      nameAsc: "Tên A đến Z",
      nameDesc: "Tên Z đến A",
      results: "kết quả phù hợp",
      clear: "Xóa bộ lọc",
      emptyTitle: "Chưa tìm thấy theme phù hợp",
      emptyDesc: "Hãy thử từ khóa ngắn hơn hoặc bỏ bớt một bộ lọc.",
      errorTitle: "Chưa thể tải thư viện",
      errorDesc: "Kết nối đến máy chủ đang gặp sự cố. Vui lòng thử lại.",
    },
    detail: {
      back: "Quay lại thư viện",
      preview: "Ảnh xem trước",
      previewDescription: "Cover và các mockup cho thấy theme hiển thị thực tế trên điện thoại.",
      imageUnit: "hình",
      about: "Về giao diện này",
      platform: "Nền tảng",
      categories: "Danh mục",
      access: "Quyền truy cập",
      creator: "Người sáng tạo",
      related: "Có thể bạn cũng thích",
      relatedDesc: "Những giao diện cùng phong cách để bạn khám phá tiếp.",
      noDescription: "Creator chưa thêm mô tả cho theme này.",
      packageTitle: "Gói file theme",
      packageDescription: "Sau khi xác thực, Loichoi sẽ mở gói Google Drive chứa các file cài đặt và tài nguyên đi kèm. Link tải không xuất hiện trong dữ liệu công khai.",
      packageIncludes: "Nhiều file cài đặt và tài nguyên",
    },
    download: {
      action: "Tải bộ file",
      checking: "Đang kiểm tra quyền...",
      success: "Đã mở liên kết tải xuống",
      login: "Bạn cần đăng nhập trước khi tải giao diện.",
      forbidden: "Tài khoản của bạn chưa đủ quyền tải giao diện này.",
      missing: "Theme này không còn tồn tại hoặc chưa được phát hành.",
      rate: "Bạn thao tác tải quá nhanh. Vui lòng chờ một phút rồi thử lại.",
      error: "Máy chủ chưa thể xử lý lượt tải. Vui lòng thử lại.",
      loginAction: "Đăng nhập",
      discordAction: "Mở Discord",
    },
    categories: {
      eyebrow: "Bộ sưu tập theo chủ đề",
      title: "Chọn phong cách bạn yêu thích",
      description: "Từ pastel dịu nhẹ đến anime cá tính, mỗi danh mục là một thế giới riêng.",
      empty: "Chưa có danh mục công khai.",
      error: "Chưa thể tải danh mục lúc này.",
    },
    trending: {
      eyebrow: "Được cộng đồng yêu thích",
      title: "Giao diện đang thịnh hành",
      description: "Xếp hạng theo lượt tải để bạn không bỏ lỡ những thiết kế nổi bật.",
    },
    footer: {
      description: "Thư viện theme bàn phím điện thoại với nhiều ảnh xem trước và bộ file tải cho iOS, Android.",
      discover: "Khám phá",
      account: "Tài khoản",
      rights: "Loichoi. Nội dung được bảo lưu.",
    },
  },
  en: {
    nav: { explore: "Explore", categories: "Categories", trending: "Trending" },
    common: {
      viewAll: "View all",
      loading: "Loading...",
      retry: "Try again",
      downloads: "downloads",
      keyboards: "themes",
      previous: "Previous",
      next: "Next",
      page: "Page",
      of: "of",
    },
    home: {
      badge: "Mobile keyboard theme library for iOS and Android",
      title: "A little joy in every keystroke",
      description:
        "Browse rich previews and download complete pastel, anime, and minimalist mobile keyboard theme packs.",
      search: "Search Sakura, anime, pastel...",
      searchAction: "Find themes",
      featured: "Featured today",
      featuredDesc: "Mobile keyboard themes loved by the community and handpicked by Loichoi.",
      trending: "Trending now",
      trendingDesc: "The most downloaded themes in the collection.",
      categories: "Explore by style",
      categoriesDesc: "Start with a category that feels like you.",
      discordTitle: "Let's make keyboards beautiful together",
      discordDesc: "Join Discord for community themes, keyboard screenshots, and creator conversations.",
      discordAction: "Join Discord",
    },
    explore: {
      eyebrow: "Mobile theme library",
      title: "Find a keyboard theme made for you",
      description: "Filter by style and platform. Every choice stays in the URL.",
      search: "Search theme names...",
      category: "Category",
      allCategories: "All categories",
      platform: "Platform",
      allPlatforms: "All platforms",
      sort: "Sort by",
      latest: "Newest",
      popular: "Most popular",
      liked: "Most liked",
      nameAsc: "Name A to Z",
      nameDesc: "Name Z to A",
      results: "matching results",
      clear: "Clear filters",
      emptyTitle: "No matching themes yet",
      emptyDesc: "Try a shorter search or remove one of the filters.",
      errorTitle: "The library could not load",
      errorDesc: "The server connection is having trouble. Please try again.",
    },
    detail: {
      back: "Back to library",
      preview: "Preview images",
      previewDescription: "Cover art and mockups show how this theme looks on a real phone.",
      imageUnit: "images",
      about: "About this theme",
      platform: "Platform",
      categories: "Categories",
      access: "Access",
      creator: "Creator",
      related: "You may also like",
      relatedDesc: "More themes with a similar style to continue exploring.",
      noDescription: "The creator has not added a description yet.",
      packageTitle: "Theme file pack",
      packageDescription: "After authorization, Loichoi opens the protected Google Drive package containing installation files and bundled assets. The download link is never exposed by the public API.",
      packageIncludes: "Multiple installation files and assets",
    },
    download: {
      action: "Download file pack",
      checking: "Checking access...",
      success: "Your download link is opening",
      login: "Please sign in before downloading this theme.",
      forbidden: "Your account does not have access to this theme yet.",
      missing: "This theme no longer exists or is not published.",
      rate: "There have been too many download requests. Please wait a minute and try again.",
      error: "The server could not process this download. Please try again.",
      loginAction: "Sign in",
      discordAction: "Open Discord",
    },
    categories: {
      eyebrow: "Collections by topic",
      title: "Choose a style you love",
      description: "From gentle pastels to bold anime, every category has a world of its own.",
      empty: "There are no public categories yet.",
      error: "Categories are unavailable right now.",
    },
    trending: {
      eyebrow: "Loved by the community",
      title: "Themes trending now",
      description: "Ranked by downloads so you never miss a standout design.",
    },
    footer: {
      description: "Mobile keyboard themes with rich previews and downloadable file packs for iOS and Android.",
      discover: "Discover",
      account: "Account",
      rights: "Loichoi. All content reserved.",
    },
  },
} as const;

export function getPublicCopy(language: Language) {
  return copy[language];
}
